---
- name: remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: set init 3
  command: init 3
  ignore_errors: yes

- name: set default target to multi-user
  command: systemctl set-default multi-user.target
  ignore_errors: yes

- name: install driver packages
  apt:
    name: "{{ nvidia_driver_package_version | ternary(item+'='+nvidia_driver_package_version, item) }}"
    state: "{{ nvidia_driver_package_state }}"
    autoremove: "{{ nvidia_driver_package_state == 'absent' }}"
    purge: "{{ nvidia_driver_package_state == 'absent' }}"
  loop: "{{ nvidia_driver_ubuntu_packages }}"
  register: install_driver
  environment: "{{proxy_env if proxy_env is defined else {}}}"

- name: Start the nvidia-fabricmanager service otherwise
  systemd:
    daemon_reload: yes
    name: "nvidia-fabricmanager.service"
    state: "started"
    enabled: true
  when: '"nvidia-fabricmanager.service" not in services'
